// src/components/ListenSleepTimer.tsx
import { memo, useEffect, useState } from "react"
import { usePlayer } from "../context/PlayerContext"
import { useI18n } from "../i18n/useI18n"
import {
  formatSleepTimerRemainingMs,
  parseSleepTimerCustomMinutes,
} from "../lib/sleepTimerFormat"
import { UiChevronRight, UiHistory } from "./RekordUiIcons"

const PRESETS = [15, 30, 60] as const

function digitsOnly(value: string): string {
  return value.replace(/\D/g, "")
}

export const ListenSleepTimer = memo(function ListenSleepTimer() {
  const p = usePlayer()
  const { t } = useI18n()
  const [open, setOpen] = useState(false)
  const [now, setNow] = useState(() => Date.now())
  const [customHours, setCustomHours] = useState("0")
  const [customMinutes, setCustomMinutes] = useState("45")
  const [customError, setCustomError] = useState(false)

  useEffect(() => {
    if (!p.sleepTimerEndsAt) return
    setNow(Date.now())
    const id = window.setInterval(() => setNow(Date.now()), 1000)
    return () => window.clearInterval(id)
  }, [p.sleepTimerEndsAt])

  const remainingMs = p.sleepTimerEndsAt
    ? Math.max(0, p.sleepTimerEndsAt - now)
    : 0
  const active = Boolean(p.sleepTimerEndsAt && remainingMs > 0)
  const remainingLabel = formatSleepTimerRemainingMs(remainingMs)

  const startTimer = (minutes: number) => {
    p.setSleepTimer(minutes)
    setNow(Date.now())
    setCustomError(false)
    setOpen(false)
  }

  const startCustom = () => {
    const total = parseSleepTimerCustomMinutes(customHours, customMinutes)
    if (total == null) {
      setCustomError(true)
      return
    }
    startTimer(total)
  }

  return (
    <section
      className={`listen-sleep-timer${open ? " is-open" : ""}${active ? " is-active" : ""}`}
      aria-label={t("listen.sleepTimerAria")}
    >
      <button
        type="button"
        className="listen-sleep-timer__toggle"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
      >
        <span className="listen-sleep-timer__toggle-main">
          <UiHistory className="listen-sleep-timer__ic" aria-hidden />
          <span className="listen-sleep-timer__toggle-title">
            {t("listen.sleepTimer")}
          </span>
          {active ? (
            <span className="listen-sleep-timer__badge" aria-live="polite">
              {remainingLabel}
            </span>
          ) : null}
        </span>
        <UiChevronRight
          className={
            open ? "listen-sleep-timer__chev is-open" : "listen-sleep-timer__chev"
          }
          aria-hidden
        />
      </button>

      {open ? (
        <div className="listen-sleep-timer__panel">
          <div className="listen-sleep-timer__row">
            {PRESETS.map((min) => (
              <button
                key={min}
                type="button"
                className="ghost-btn ghost-btn--sm"
                onClick={() => startTimer(min)}
              >
                {t(
                  min === 15
                    ? "player.sleepTimer15"
                    : min === 30
                      ? "player.sleepTimer30"
                      : "player.sleepTimer60",
                )}
              </button>
            ))}

            <label className="listen-sleep-timer__field">
              <span className="listen-sleep-timer__field-label">
                {t("listen.sleepTimerHours")}
              </span>
              <input
                type="text"
                className="ghost-input listen-sleep-timer__input"
                inputMode="numeric"
                autoComplete="off"
                aria-label={t("listen.sleepTimerHours")}
                value={customHours}
                onChange={(event) => {
                  setCustomError(false)
                  setCustomHours(digitsOnly(event.target.value))
                }}
              />
            </label>

            <label className="listen-sleep-timer__field">
              <span className="listen-sleep-timer__field-label">
                {t("listen.sleepTimerMinutes")}
              </span>
              <input
                type="text"
                className="ghost-input listen-sleep-timer__input"
                inputMode="numeric"
                autoComplete="off"
                aria-label={t("listen.sleepTimerMinutes")}
                value={customMinutes}
                onChange={(event) => {
                  setCustomError(false)
                  setCustomMinutes(digitsOnly(event.target.value))
                }}
                onKeyDown={(event) => {
                  if (event.key === "Enter") startCustom()
                }}
              />
            </label>

            <button
              type="button"
              className="ghost-btn ghost-btn--sm"
              onClick={startCustom}
            >
              {t("listen.sleepTimerStart")}
            </button>

            {active ? (
              <button
                type="button"
                className="text-btn listen-sleep-timer__cancel"
                onClick={() => p.setSleepTimer(null)}
              >
                {t("listen.sleepTimerCancel")}
              </button>
            ) : null}
          </div>

          {customError ? (
            <p className="listen-sleep-timer__error subtle sm" role="alert">
              {t("listen.sleepTimerInvalid")}
            </p>
          ) : null}
        </div>
      ) : null}
    </section>
  )
})

// next/apps/client-ui/src/components/ListenSleepTimer.svelte
<script lang="ts">
  import UiIcon from "./icons/UiIcon.svelte";
  import { t } from "../lib/i18n.svelte";
  import { player } from "../lib/player";
  import { session } from "../lib/session.svelte";

  const PRESETS = [15, 30, 60] as const;

  let open = $state(false);
  let now = $state(Date.now());
  let customHours = $state("0");
  let customMinutes = $state("45");
  let customError = $state(false);

  $effect(() => {
    if (!session.sleepTimerEndsAt) return;
    now = Date.now();
    const id = window.setInterval(() => {
      now = Date.now();
    }, 1000);
    return () => window.clearInterval(id);
  });

  const remainingMs = $derived(
    session.sleepTimerEndsAt ? Math.max(0, session.sleepTimerEndsAt - now) : 0,
  );
  const active = $derived(Boolean(session.sleepTimerEndsAt && remainingMs > 0));
  const remainingLabel = $derived.by(() => {
    const totalSec = Math.floor(remainingMs / 1000);
    const h = Math.floor(totalSec / 3600);
    const m = Math.floor((totalSec % 3600) / 60);
    const s = totalSec % 60;
    if (h > 0) {
      return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
    }
    return `${m}:${s.toString().padStart(2, "0")}`;
  });

  function digitsOnly(value: string): string {
    return value.replace(/\D/g, "");
  }

  function presetLabel(min: (typeof PRESETS)[number]): string {
    if (min === 15) return t("player.sleepTimer15");
    if (min === 30) return t("player.sleepTimer30");
    return t("player.sleepTimer60");
  }

  function startTimer(minutes: number) {
    player.setSleepTimer(minutes);
    now = Date.now();
    customError = false;
    open = false;
  }

  function startCustom() {
    const h = Number(customHours) || 0;
    const m = Number(customMinutes) || 0;
    const total = h * 60 + m;
    if (total <= 0 || h > 12) {
      customError = true;
      return;
    }
    startTimer(total);
  }
</script>

<section
  class="listen-sleep-timer"
  class:is-open={open}
  class:is-active={active}
  aria-label={t("listen.sleepTimerAria")}
>
  <button
    type="button"
    class="listen-sleep-timer__toggle"
    onclick={() => (open = !open)}
    aria-expanded={open}
  >
    <span class="listen-sleep-timer__toggle-main">
      <UiIcon name="history" class="listen-sleep-timer__ic" />
      <span class="listen-sleep-timer__toggle-title">{t("listen.sleepTimer")}</span>
      {#if active}
        <span class="listen-sleep-timer__badge" aria-live="polite">{remainingLabel}</span>
      {/if}
    </span>
    <UiIcon
      name="chevronRight"
      class="listen-sleep-timer__chev{open ? ' is-open' : ''}"
    />
  </button>

  {#if open}
    <div class="listen-sleep-timer__panel">
      <div class="listen-sleep-timer__row">
        {#each PRESETS as min}
          <button
            type="button"
            class="ghost-btn ghost-btn--sm"
            onclick={() => startTimer(min)}
          >
            {presetLabel(min)}
          </button>
        {/each}

        <label class="listen-sleep-timer__field">
          <span class="listen-sleep-timer__field-label">{t("listen.sleepTimerHours")}</span>
          <input
            type="text"
            class="ghost-input listen-sleep-timer__input"
            inputmode="numeric"
            autocomplete="off"
            aria-label={t("listen.sleepTimerHours")}
            value={customHours}
            oninput={(e) => {
              customError = false;
              customHours = digitsOnly(e.currentTarget.value);
            }}
          />
        </label>

        <label class="listen-sleep-timer__field">
          <span class="listen-sleep-timer__field-label">{t("listen.sleepTimerMinutes")}</span>
          <input
            type="text"
            class="ghost-input listen-sleep-timer__input"
            inputmode="numeric"
            autocomplete="off"
            aria-label={t("listen.sleepTimerMinutes")}
            value={customMinutes}
            oninput={(e) => {
              customError = false;
              customMinutes = digitsOnly(e.currentTarget.value);
            }}
            onkeydown={(e) => {
              if (e.key === "Enter") startCustom();
            }}
          />
        </label>

        <button type="button" class="ghost-btn ghost-btn--sm" onclick={startCustom}>
          {t("listen.sleepTimerStart")}
        </button>

        {#if active}
          <button
            type="button"
            class="text-btn listen-sleep-timer__cancel"
            onclick={() => player.setSleepTimer(null)}
          >
            {t("listen.sleepTimerCancel")}
          </button>
        {/if}
      </div>
      {#if customError}
        <p class="listen-sleep-timer__error warnline" role="alert">
          {t("listen.sleepTimerInvalid")}
        </p>
      {/if}
    </div>
  {/if}
</section>
