// src/components/QrCodeImg.tsx
import { useEffect, useState } from "react";
import QRCode from "qrcode";

/** QR generato in locale (niente servizi esterni: funziona offline e l'URL non esce dalla LAN). */
export function QrCodeImg({
  value,
  size = 220,
  className,
  alt = "",
}: {
  value: string;
  size?: number;
  className?: string;
  alt?: string;
}) {
  const [dataUrl, setDataUrl] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    QRCode.toDataURL(value, {
      width: size,
      margin: 2,
      errorCorrectionLevel: "M",
      color: { dark: "#000000", light: "#ffffff" },
    })
      .then((u) => {
        if (active) setDataUrl(u);
      })
      .catch(() => {
        if (active) setDataUrl(null);
      });
    return () => {
      active = false;
    };
  }, [value, size]);

  if (!dataUrl) return null;
  return (
    <img
      src={dataUrl}
      width={size}
      height={size}
      className={className}
      alt={alt}
    />
  );
}

// next/apps/client-ui/src/components/QrCodeImg.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  let {
    value,
    size = 220,
    alt = "",
    class: className = "",
  }: {
    value: string;
    size?: number;
    alt?: string;
    class?: string;
  } = $props();

  let dataUrl = $state<string | null>(null);
  let gen = 0;

  $effect(() => {
    const v = value;
    const s = size;
    const id = ++gen;
    dataUrl = null;
    if (!v) return;

    let cancelled = false;
    void (async () => {
      try {
        const QRCode = (await import("qrcode")).default;
        const url = await QRCode.toDataURL(v, {
          width: s,
          margin: 2,
          errorCorrectionLevel: "M",
          color: { dark: "#000000", light: "#ffffff" },
        });
        if (!cancelled && id === gen) dataUrl = url;
      } catch {
        if (!cancelled && id === gen) dataUrl = null;
      }
    })();

    return () => {
      cancelled = true;
    };
  });

  onDestroy(() => {
    gen += 1;
  });
</script>

{#if dataUrl}
  <img src={dataUrl} width={size} height={size} class={className} {alt} />
{/if}
