// src/components/ThemePicker.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { CustomThemeDialog } from "./CustomThemeDialog";
import { useI18n } from "../i18n/useI18n";
import { DEFAULT_CUSTOM_THEME, THEME_CATALOG } from "../lib/themeCatalog";
import type { CustomThemeSettings, ThemeMode } from "../types";

function ThemeStrip({
  bg,
  bgImageUrl,
  section,
  accent,
  accent2,
  t,
}: {
  bg: string;
  bgImageUrl?: string | null;
  section: string;
  accent: string;
  accent2: string;
  t: (k: string) => string;
}) {
  return (
    <span className="theme-picker__strip" aria-hidden>
      <span
        className="theme-picker__strip-seg theme-picker__strip-seg--bg"
        style={
          bgImageUrl
            ? {
                backgroundImage: `url("${bgImageUrl}")`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }
            : { background: bg }
        }
        title={t("themePicker.stripBg")}
      />
      <span className="theme-picker__strip-seg" style={{ background: section }} title={t("themePicker.stripSection")} />
      <span className="theme-picker__strip-seg" style={{ background: accent }} title={t("themePicker.stripAccent1")} />
      <span className="theme-picker__strip-seg" style={{ background: accent2 }} title={t("themePicker.stripAccent2")} />
    </span>
  );
}

export function ThemePicker({
  value,
  onChange,
  customTheme = DEFAULT_CUSTOM_THEME,
  onCustomThemeChange,
  customThemeBgPreviewUrl = null,
  onCustomThemeBgUpload,
  onCustomThemeBgClear,
}: {
  value: ThemeMode;
  onChange: (theme: ThemeMode) => void;
  customTheme?: CustomThemeSettings;
  onCustomThemeChange?: (theme: CustomThemeSettings) => void;
  customThemeBgPreviewUrl?: string | null;
  onCustomThemeBgUpload?: (
    file: File,
  ) => Promise<{ bgImage: string; bgImageRev: number }>;
  onCustomThemeBgClear?: () => Promise<void>;
}) {
  const { t } = useI18n();
  const [open, setOpen] = useState(false);
  const [customDialogOpen, setCustomDialogOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const curBase = THEME_CATALOG.find((th) => th.id === value) ?? THEME_CATALOG[0];
  const cur =
    curBase.id === "custom" ? { ...curBase, ...customTheme } : curBase;
  const bgPreviewUrl =
    value === "custom" &&
    customTheme.bgMode === "image" &&
    customTheme.bgImage
      ? customThemeBgPreviewUrl
      : null;

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onDoc);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDoc);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  const pick = useCallback(
    (id: ThemeMode) => {
      onChange(id);
      setOpen(false);
    },
    [onChange],
  );

  const saveCustomTheme = useCallback(
    (next: CustomThemeSettings) => {
      onCustomThemeChange?.(next);
      if (value !== "custom") onChange("custom");
    },
    [onChange, onCustomThemeChange, value],
  );

  const groups = [
    { id: "dual", label: t("themePicker.groupDual") },
    { id: "dark", label: t("themePicker.groupDark") },
    { id: "light", label: t("themePicker.groupLight") },
    { id: "color", label: t("themePicker.groupColor") },
    { id: "custom", label: t("themePicker.groupCustom") },
  ] as const;

  return (
    <div className={`theme-picker${open ? " is-open" : ""}`} ref={rootRef}>
      <button
        type="button"
        className="theme-picker__btn"
        aria-haspopup="listbox"
        aria-expanded={open}
        onClick={() => setOpen((o) => !o)}
      >
        <span className="theme-picker__label">{t(`theme.${cur.id}`)}</span>
        <ThemeStrip
          bg={cur.bg}
          bgImageUrl={bgPreviewUrl}
          section={cur.section}
          accent={cur.accent}
          accent2={cur.accent2}
          t={t}
        />
      </button>
      {open ? (
        <ul className="theme-picker__menu" role="listbox">
          {groups.map((group) => {
            const entries = THEME_CATALOG.filter((entry) => entry.group === group.id);
            if (!entries.length) return null;
            return (
              <li className="theme-picker__group" key={group.id} role="none">
                <div className="theme-picker__group-label">{group.label}</div>
                <ul className="theme-picker__group-list" role="none">
                  {entries.map((entry) => {
                    const preview =
                      entry.id === "custom" ? { ...entry, ...customTheme } : entry;
                    return (
                      <li key={entry.id} role="none">
                        <button
                          type="button"
                          role="option"
                          aria-selected={entry.id === value}
                          className={
                            entry.id === value
                              ? "theme-picker__opt is-active"
                              : "theme-picker__opt"
                          }
                          onClick={() => pick(entry.id)}
                        >
                          <span className="theme-picker__name">{t(`theme.${entry.id}`)}</span>
                          <ThemeStrip
                            bg={preview.bg}
                            bgImageUrl={
                              entry.id === "custom" &&
                              customTheme.bgMode === "image" &&
                              customTheme.bgImage
                                ? customThemeBgPreviewUrl
                                : null
                            }
                            section={preview.section}
                            accent={preview.accent}
                            accent2={preview.accent2}
                            t={t}
                          />
                        </button>
                      </li>
                    );
                  })}
                </ul>
              </li>
            );
          })}
        </ul>
      ) : null}
      {value === "custom" ? (
        <button
          type="button"
          className="ghost-btn ghost-btn--sm theme-picker__customize-btn"
          onClick={() => setCustomDialogOpen(true)}
        >
          {t("themePicker.customEditBtn")}
        </button>
      ) : null}
      {onCustomThemeBgUpload && onCustomThemeBgClear ? (
        <CustomThemeDialog
          open={customDialogOpen}
          initialTheme={customTheme}
          onSave={saveCustomTheme}
          onClose={() => setCustomDialogOpen(false)}
          onUploadBg={onCustomThemeBgUpload}
          onClearBg={onCustomThemeBgClear}
        />
      ) : null}
    </div>
  );
}

// next/apps/client-ui/src/components/ThemePicker.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    customThemeBgImageCss,
    objectFitForBgImageFit,
  } from "../lib/customThemeBgFit";
  import { customThemeBgImageUrl } from "../lib/customThemeBgUrl";
  import { t } from "../lib/i18n.svelte";
  import {
    THEME_CATALOG,
    THEME_GROUPS,
    catalogEntry,
    type CustomThemeBgImageFit,
    type CustomThemeSettings,
  } from "../lib/themeCatalog";
  import type { UiTheme } from "../lib/userPrefs";
  import CustomThemeDialog from "./CustomThemeDialog.svelte";

  let {
    value,
    customTheme,
    onchange,
    onCustomThemeChange,
    ariaLabel = "",
  }: {
    value: UiTheme;
    customTheme: CustomThemeSettings;
    onchange: (theme: UiTheme) => void;
    onCustomThemeChange: (theme: CustomThemeSettings) => void;
    ariaLabel?: string;
  } = $props();

  let open = $state(false);
  let customOpen = $state(false);
  let rootEl: HTMLDivElement | undefined = $state();

  const current = $derived.by(() => {
    const base = catalogEntry(value);
    return value === "custom" ? { ...base, ...customTheme } : base;
  });

  const currentLabel = $derived(
    value === "midnight"
      ? `${t(`theme.${value}`)} (${t("settings.themeDefault")})`
      : t(`theme.${value}`),
  );

  const customBgPreviewUrl = $derived(
    customTheme.bgMode === "image" && customTheme.bgImage
      ? customThemeBgImageUrl(customTheme.bgImageRev ?? undefined)
      : null,
  );

  function pick(id: string) {
    onchange(id as UiTheme);
    open = false;
    if (id === "custom") customOpen = true;
  }

  function onDocPointer(e: PointerEvent) {
    if (!open || !rootEl) return;
    if (!rootEl.contains(e.target as Node)) open = false;
  }

  function onKey(e: KeyboardEvent) {
    if (e.key === "Escape" && open) open = false;
  }

  onMount(() => {
    document.addEventListener("pointerdown", onDocPointer);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("pointerdown", onDocPointer);
      document.removeEventListener("keydown", onKey);
    };
  });
</script>

{#snippet themeStrip(
  bg: string,
  section: string,
  accent: string,
  accent2: string,
  bgImageUrl: string | null = null,
  bgImageFit: CustomThemeBgImageFit | undefined = undefined,
  bgImageExt: string | null | undefined = undefined,
)}
  {@const fitCss = customThemeBgImageCss(bgImageFit)}
  {@const obj = objectFitForBgImageFit(bgImageFit)}
  <span class="theme-picker__strip" aria-hidden="true">
    {#if bgImageExt === "gif" && bgImageUrl}
      <img
        class="theme-picker__strip-seg theme-picker__strip-seg--bg"
        src={bgImageUrl}
        alt=""
        style:background-color={bg}
        style:object-fit={obj.objectFit}
        style:object-position={obj.objectPosition}
        title={t("themePicker.stripBg")}
      />
    {:else if bgImageUrl}
      <span
        class="theme-picker__strip-seg theme-picker__strip-seg--bg"
        style:background-color={bg}
        style:background-image={`url("${bgImageUrl}")`}
        style:background-size={fitCss.size}
        style:background-position={fitCss.position}
        style:background-repeat={fitCss.repeat}
        title={t("themePicker.stripBg")}
      ></span>
    {:else}
      <span
        class="theme-picker__strip-seg theme-picker__strip-seg--bg"
        style:background={bg}
        title={t("themePicker.stripBg")}
      ></span>
    {/if}
    <span
      class="theme-picker__strip-seg"
      style:background={section}
      title={t("themePicker.stripSection")}
    ></span>
    <span
      class="theme-picker__strip-seg"
      style:background={accent}
      title={t("themePicker.stripAccent1")}
    ></span>
    <span
      class="theme-picker__strip-seg"
      style:background={accent2}
      title={t("themePicker.stripAccent2")}
    ></span>
  </span>
{/snippet}

<div class="theme-picker" class:is-open={open} bind:this={rootEl}>
  <button
    type="button"
    class="theme-picker__btn"
    aria-haspopup="listbox"
    aria-expanded={open}
    aria-label={ariaLabel || t("settings.themeAria")}
    onclick={() => (open = !open)}
  >
    <span class="theme-picker__label">{currentLabel}</span>
    {@render themeStrip(
      current.bg,
      current.section,
      current.accent,
      current.accent2,
      value === "custom" ? customBgPreviewUrl : null,
      value === "custom" ? customTheme.bgImageFit : undefined,
      value === "custom" ? customTheme.bgImage : undefined,
    )}
  </button>

  {#if open}
    <ul class="theme-picker__menu" role="listbox">
      {#each THEME_GROUPS as group (group.id)}
        {@const entries = THEME_CATALOG.filter((e) => e.group === group.id)}
        {#if entries.length}
          <li class="theme-picker__group" role="none">
            <div class="theme-picker__group-label">{t(group.labelKey)}</div>
            <ul class="theme-picker__group-list" role="none">
              {#each entries as entry (entry.id)}
                {@const preview =
                  entry.id === "custom" ? { ...entry, ...customTheme } : entry}
                {@const label =
                  entry.id === "midnight"
                    ? `${t(`theme.${entry.id}`)} (${t("settings.themeDefault")})`
                    : t(`theme.${entry.id}`)}
                <li role="none">
                  <button
                    type="button"
                    role="option"
                    aria-selected={entry.id === value}
                    class="theme-picker__opt"
                    class:is-active={entry.id === value}
                    onclick={() => pick(entry.id)}
                  >
                    <span class="theme-picker__name">{label}</span>
                    {@render themeStrip(
                      preview.bg,
                      preview.section,
                      preview.accent,
                      preview.accent2,
                      entry.id === "custom" &&
                        customTheme.bgMode === "image" &&
                        customTheme.bgImage
                        ? customBgPreviewUrl
                        : null,
                      entry.id === "custom" ? customTheme.bgImageFit : undefined,
                      entry.id === "custom" ? customTheme.bgImage : undefined,
                    )}
                  </button>
                </li>
              {/each}
            </ul>
          </li>
        {/if}
      {/each}
    </ul>
  {/if}

  {#if value === "custom"}
    <button
      type="button"
      class="theme-picker__customize-btn"
      onclick={() => (customOpen = true)}
    >
      {t("themePicker.customEditBtn")}
    </button>
  {/if}
</div>

<CustomThemeDialog
  open={customOpen}
  theme={customTheme}
  onclose={() => (customOpen = false)}
  onsave={onCustomThemeChange}
/>
