// next/apps/client-ui/src/components/PlayCollectionButton.svelte
<script lang="ts">
  import { Button } from "@rekord/ui";
  import UiIcon from "./icons/UiIcon.svelte";

  let {
    label = "Shuffle",
    disabled = false,
    onclick,
  }: {
    label?: string;
    disabled?: boolean;
    onclick?: () => void;
  } = $props();
</script>

<Button class="play-collection-btn" {disabled} {onclick}>
  <UiIcon name="shuffle" />
  {label}
</Button>

// src/components/PlayCollectionButton.tsx
import { UiShuffle } from "./RekordUiIcons";

type Props = {
  label: string;
  disabled?: boolean;
  onClick: () => void;
};

export function PlayCollectionButton({ label, disabled = false, onClick }: Props) {
  return (
    <button
      type="button"
      className="primary-btn play-collection-btn"
      disabled={disabled}
      onClick={onClick}
    >
      <UiShuffle className="play-collection-btn__ic" aria-hidden />
      {label}
    </button>
  );
}
